---
# tasks file for hostname
- name: update the hostname
  hostname:
    name: "{{ hostname }}"
  tags: [configuration, hostname]

- name: update the hostsname - /etc/hostname file
  template:
    src: etc/hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags: [configuration, hostname]

- name: update the hostsname - /etc/hosts file
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags: [configuration, hostname]

#- name: update the hostname - /etc/hosts file
#  lineinfile: >
#    dest=/etc/hosts
#    regexp='.*{{ item }}$'
#    line="{{ hostvars[item].private_address }} {{ hostvars[item].inventory_hostname }}"
#    state=present
#  when: hostvars[item].private_address is defined
#  with_items: groups['all']
